version: '3.8'

services:
  demo_one:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo_one
    container_name: demo_one
    ports:
      - "8080:8080"
    restart: always

  demo_two:
    build:
      context: ../demoTwo
      dockerfile: Dockerfile
    image: demo_two
    container_name: demo_two
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      - demo_one
